### ISSUE TITLE
vaPutSurface take too much time up to 40ms

### ISSUE THREAD

**Issue by waiter89** [intel/libva#259]
(gdb) bt
#0  0x00007ffff2fb4a17 in ioctl () from /lib64/libc.so.6
#1  0x00007fffe01b8bf8 in drmIoctl () from /usr/lib64/libdrm.so.2
#2  0x00007fffd6455578 in ?? () from /usr/lib64/libdrm_intel.so.1
#3  0x00007fffd64557a6 in ?? () from /usr/lib64/libdrm_intel.so.1
#4  0x00007fffd67228bf in intel_batchbuffer_flush () from /usr/lib64/dri/i965_drv_video.so
#5  0x00007fffd671d2eb in gen8_render_put_surface () from /usr/lib64/dri/i965_drv_video.so
#6  0x00007fffd6717f95 in intel_render_put_surface () from /usr/lib64/dri/i965_drv_video.so
#7  0x00007fffd6732b96 in i965_put_surface_dri () from /usr/lib64/dri/i965_drv_video.so
#8  0x00007fffd66ec682 in i965_PutSurface () from /usr/lib64/dri/i965_drv_video.so
#9  0x00007fffd7c96dd6 in vaPutSurface () from ./plugins/dec/exp_sw.dec
#10 0x00007fffd79ffd41 in sw_begin_draw (Acodec=0x2726900) at ../shanwei.c:460
#11 0x00007fffe27881e1 in sw_begin_draw (Aplayer=0x27263d0) at ../shanwei_proc/shanwei_proc.c:147
#12 0x000000000056c2c3 in Frame::paintEvent (this=0x272ab70, Ae=0x7fffffffdd00)
    at ../../sharedsrc/guilingFrame/frame.cpp:1045
#13 0x00007ffff445d970 in QWidget::event(QEvent*) () from /usr/lib64/libQtGui.so.4
#14 0x00007ffff440711c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib64/libQtGui.so.4
#15 0x00007ffff440e01c in QApplication::notify(QObject*, QEvent*) () from /usr/lib64/libQtGui.so.4

**Comment by waiter89** [comment]
CPU N3150
Linux Opensuse 64bit  4.6.3-1-default  
Monitor 1920x1080

**Comment by XinfengZhang** [comment]
seems a driver issue, could you file PR on https://github.com/intel/intel-vaapi-driver
