### ISSUE TITLE
drmIoctl death loop when I use ffmpeg h264 encoder 

### ISSUE THREAD

**Issue by gumjum** [intel/libva#322]
Thread 3 (Thread 0x7fb83affd700 (LWP 24207)):
#0  0x00007fb8874b7be7 in ioctl () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007fb88183e738 in drmIoctl () from /usr/lib/x86_64-linux-gnu/libdrm.so.2
#2  0x00007fb86004e6f9 in ?? () from /usr/lib/x86_64-linux-gnu/libdrm_intel.so.1
#3  0x00007fb85511a27a in ?? () from /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
#4  0x00007fb8550c7ba3 in ?? () from /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
#5  0x00007fb8550c8b3d in ?? () from /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
#6  0x00007fb8550d46df in ?? () from /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
#7  0x00007fb855124c5b in ?? () from /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
#8  0x00007fb883b13c1f in vaEndPicture () from /usr/lib/x86_64-linux-gnu/libva.so.1
#9  0x00007fb8863a41d2 in ?? () from /usr/local/lib/libavcodec.so.57
#10 0x00007fb8863a4450 in ?? () from /usr/local/lib/libavcodec.so.57
#11 0x00007fb8863a4b4e in ?? () from /usr/local/lib/libavcodec.so.57
#12 0x00007fb885fa8422 in avcodec_encode_video2 () from /usr/local/lib/libavcodec.so.57
#13 0x00007fb885fa8725 in ?? () from /usr/local/lib/libavcodec.so.57
#14 0x00007fb885fa887f in avcodec_send_frame () from /usr/local/lib/libavcodec.so.57
#15 0x00007fb88b3b24fc in avc_encode_frame (encoder=0x7fb82c000900, frame=0x7fb82c01ad80) at avc_hw_encoder.c:173
#16 0x00007fb88b3b2b63 in avc_hw_encode (base=0x7fb82c000900, 
    in=0x7fb87bd5f000 "\335|\312\177\313|\313y\313}\313x\311}\312x\314\177\322y\341\177\323}y|P}K~7}D\200IyK\177KyO|P|N|JzD{-z(}*|0\177\062~2\200>\213AxB\241LrN\206M~M{N~NxMyKrN{OyN\177O|N\177KyJ\200MwL\177K{I\177IwJ\177IrI\177KvK\177LvD\200:y9\177\060w>\207Nrb\202vr\206\204\204r\222\205\227g\221\211\214d\211\211\205e\202\217{f\210\215\242m\253\203\254s\254\177\251u\217\203\241s\246\207\247n\245\205\244k\246\177\250w\253x\257~\257s\243}\205n^|Aw5\207"..., len=614400, 
    out=0x7fb83affcc40) at avc_hw_encoder.c:373

**Comment by XinfengZhang** [comment]
@gumjum , it should be a driver issue, please help to file issue on https://github.com/intel/intel-vaapi-driver, thanks

**Comment by XinfengZhang** [comment]
@gumjum , also , if you also can reproduce the issue with iHD driver, please file issue on https://github.com/intel/media-driver
