### ISSUE TITLE
Segmentation fault with X11 display

### ISSUE THREAD

**Issue by juan-OY** [intel/libva#509]
Met segmentation fault with MediaSDK(sample_decode h624 -i ~/2.h264 -vaapi -r) or libva samples(libva-utils/putsurface)  whenever X11 is used for display. 

OS: CentOS 7.6 with upgraded kernel version 5.10.14. 
HW: TGL-U i3
libva" 2.9.0

Libva and iHD version:
libva info: VA-API version 1.9.0
libva info: User environment variable requested driver 'iHD'
libva info: Trying to open /usr/lib/dri//iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_9
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.9 (libva 2.9.0)
vainfo: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 20.3.0 (86ec0b6)
vainfo: Supported profile and entrypoints
      VAProfileNone                   : VAEntrypointVideoProc
      VAProfileNone                   : VAEntrypointStats
      VAProfileMPEG2Simple            : VAEntrypointVLD
      VAProfileMPEG2Simple            : VAEntrypointEncSlice

Software stack by gdb ./putsurface/putsurface : 

Create window0 for thread0
libva info: VA-API version 1.9.0
libva info: User environment variable requested driver 'iHD'
libva info: Trying to open /usr/lib/dri//iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_9
libva info: va_openDriver() returns 0
Loading data into surface 15.....
Enter into thread0

Program received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()
Missing separate debuginfos, use: debuginfo-install glibc-2.17-323.el7_9.x86_64 libX11-1.6.7-3.el7_9.x86_64 libXau-1.0.8-2.1.el7.x86_64 libXext-1.3.3-3.el7.x86_64 libXfixes-5.0.3-1.el7.x86_64 libffi-3.0.13-19.el7.x86_64 libgcc-4.8.5-44.el7.x86_64 libstdc++-4.8.5-44.el7.x86_64 libwayland-client-1.15.0-1.el7.x86_64 libxcb-1.13-1.el7.x86_64
(gdb) bt ful
#0  0x0000000000000000 in ?? ()
No symbol table info available.
#1  0x00007ffff7bd7a9c in do_drawable_hash (drawable=46137345, ctx=0x686410) at va_dricommon.c:74
        dri_state = <optimized out>
        index = 1
        dri_drawable = <optimized out>
#2  va_dri_get_drawable (ctx=0x686410, drawable=46137345) at va_dricommon.c:122
No locals.
#3  0x00007ffff369eff2 in DdiCodec_PutSurfaceLinuxHW (ctx=ctx@entry=0x686410, surface=surface@entry=1, draw=draw@entry=0x2c00001,
    srcx=srcx@entry=0, srcy=srcy@entry=0, srcw=srcw@entry=352, srch=288, destx=0, desty=0, destw=352, desth=288, cliprects=0x0,
number_cliprects=0, flags=0)

**Comment by XinfengZhang** [comment]
please help to check such command line
xdpyinfo | grep DRI 
&
echo $XDG_SESSION_TYPE

**Comment by 20BBrown14** [comment]
Was there any other information discovered on this? I know it's been a hot minute but I'm having a very similar issue

**Comment by chang143** [comment]
> please help to check such command line xdpyinfo | grep DRI & echo $XDG_SESSION_TYPE

I have the same problem now. Run the “xdpyinfo | grep DRI” command to print the following: “DRI2
DRI3”
Then run the “echo $XDG_SESSION_TYPE” command to print: “x11”

**Comment by chang143** [comment]
> Met segmentation fault with MediaSDK(sample_decode h624 -i ~/2.h264 -vaapi -r) or libva samples(libva-utils/putsurface) whenever X11 is used for display.
> 
> OS: CentOS 7.6 with upgraded kernel version 5.10.14. HW: TGL-U i3 libva" 2.9.0
> 
> Libva and iHD version: libva info: VA-API version 1.9.0 libva info: User environment variable requested driver 'iHD' libva info: Trying to open /usr/lib/dri//iHD_drv_video.so libva info: Found init function __vaDriverInit_1_9 libva info: va_openDriver() returns 0 vainfo: VA-API version: 1.9 (libva 2.9.0) vainfo: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 20.3.0 (86ec0b6) vainfo: Supported profile and entrypoints VAProfileNone : VAEntrypointVideoProc VAProfileNone : VAEntrypointStats VAProfileMPEG2Simple : VAEntrypointVLD VAProfileMPEG2Simple : VAEntrypointEncSlice
> 
> Software stack by gdb ./putsurface/putsurface :
> 
> Create window0 for thread0 libva info: VA-API version 1.9.0 libva info: User environment variable requested driver 'iHD' libva info: Trying to open /usr/lib/dri//iHD_drv_video.so libva info: Found init function __vaDriverInit_1_9 libva info: va_openDriver() returns 0 Loading data into surface 15..... Enter into thread0
> 
> Program received signal SIGSEGV, Segmentation fault. 0x0000000000000000 in ?? () Missing separate debuginfos, use: debuginfo-install glibc-2.17-323.el7_9.x86_64 libX11-1.6.7-3.el7_9.x86_64 libXau-1.0.8-2.1.el7.x86_64 libXext-1.3.3-3.el7.x86_64 libXfixes-5.0.3-1.el7.x86_64 libffi-3.0.13-19.el7.x86_64 libgcc-4.8.5-44.el7.x86_64 libstdc++-4.8.5-44.el7.x86_64 libwayland-client-1.15.0-1.el7.x86_64 libxcb-1.13-1.el7.x86_64 (gdb) bt ful #0 0x0000000000000000 in ?? () No symbol table info available. #1 0x00007ffff7bd7a9c in do_drawable_hash (drawable=46137345, ctx=0x686410) at va_dricommon.c:74 dri_state = index = 1 dri_drawable = #2 va_dri_get_drawable (ctx=0x686410, drawable=46137345) at va_dricommon.c:122 No locals. #3 0x00007ffff369eff2 in DdiCodec_PutSurfaceLinuxHW (ctx=ctx@entry=0x686410, surface=surface@entry=1, draw=draw@entry=0x2c00001, srcx=srcx@entry=0, srcy=srcy@entry=0, srcw=srcw@entry=352, srch=288, destx=0, desty=0, destw=352, desth=288, cliprects=0x0, number_cliprects=0, flags=0)

Hi，I also encountered the same problem as you. Have you solved the problem now? May I ask how you solved it

**Comment by chang143** [comment]
> Was there any other information discovered on this? I know it's been a hot minute but I'm having a very similar issue

Hi，I also encountered the same problem as you. Have you solved the problem now? May I ask how you solved it
